/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;

import java.awt.event.ActionListener;
import javafx.scene.AccessibleAttribute;
import javax.swing.*;

/**
 *
 * @author ariq
 */
public class main_customer extends javax.swing.JFrame {

    /**
     * Creates new form main_customer
     */
    public main_customer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_logedin = new javax.swing.JLabel();
        bt_logOut = new javax.swing.JButton();
        bt_showSchedule = new javax.swing.JButton();
        bt_OrderFilm = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bt_topUp = new javax.swing.JButton();
        btProfile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(450, 150));

        lbl_logedin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_logedin.setText("blabla, loged in");

        bt_logOut.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bt_logOut.setText("Log Out");

        bt_showSchedule.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bt_showSchedule.setText("Now Playing");

        bt_OrderFilm.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bt_OrderFilm.setText("Order");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tampilan/images/logo_coba.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        bt_topUp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bt_topUp.setText("Top Up");

        btProfile.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btProfile.setText("View Profile");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_logOut)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(146, 146, 146))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bt_showSchedule, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bt_OrderFilm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bt_topUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(223, 223, 223))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbl_logedin, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(376, 376, 376))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btProfile)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_logedin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btProfile)
                .addGap(11, 11, 11)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_showSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_OrderFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_topUp, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_logOut)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
 //isi disini
    public void setLabel (String x){
        lbl_logedin.setText("Hello "+x+" !");
    }
    
    public JButton getBtnLogOut(){
        return bt_logOut;
    }
    
    public JButton getBtnShowSchedule(){
        return bt_showSchedule;
    }
    
    public JButton getBtnOrder(){
        return bt_OrderFilm;
    }
    
    public JButton getBtnTopUp(){
        return bt_topUp;
    }
    
    public JButton getBtnProf(){
        return btProfile;
    }
    
    public void addListener (ActionListener e){
        bt_OrderFilm.addActionListener(e);
        bt_logOut.addActionListener(e);
        bt_showSchedule.addActionListener(e);
        bt_topUp.addActionListener(e);
        btProfile.addActionListener(e);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btProfile;
    private javax.swing.JButton bt_OrderFilm;
    private javax.swing.JButton bt_logOut;
    private javax.swing.JButton bt_showSchedule;
    private javax.swing.JButton bt_topUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_logedin;
    // End of variables declaration//GEN-END:variables
}
