/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;

import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author ariq
 */
public class main_admin extends javax.swing.JFrame {

    /**
     * Creates new form main_admin
     */
    public main_admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bt_addLoc = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        bt_addCin = new javax.swing.JButton();
        bt_addStud = new javax.swing.JButton();
        bt_addFilm = new javax.swing.JButton();
        bt_logout = new javax.swing.JButton();
        btJadwal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 30));

        jLabel1.setText("Admin : blabla");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Menu Admin");

        bt_addLoc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bt_addLoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tampilan/images/plus_icon_icon.png"))); // NOI18N
        bt_addLoc.setText("Tambah Lokasi          ");
        bt_addLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_addLocActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tampilan/images/logo_coba.png"))); // NOI18N

        bt_addCin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bt_addCin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tampilan/images/plus_icon_icon.png"))); // NOI18N
        bt_addCin.setText("Tambah Cinema        ");

        bt_addStud.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bt_addStud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tampilan/images/plus_icon_icon.png"))); // NOI18N
        bt_addStud.setText("Tambah Studio         ");

        bt_addFilm.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bt_addFilm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tampilan/images/plus_icon_icon.png"))); // NOI18N
        bt_addFilm.setText("Tambah Film             ");

        bt_logout.setText("Log Out");

        btJadwal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btJadwal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tampilan/images/plus_icon_icon.png"))); // NOI18N
        btJadwal.setText("Tambah Jadwal         ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(bt_logout))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 158, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(203, 203, 203))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(136, 136, 136))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(bt_addFilm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bt_addStud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bt_addCin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bt_addLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(167, 167, 167))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_addLoc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_addCin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_addFilm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_addStud)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(bt_logout)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_addLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_addLocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_addLocActionPerformed

    /**
     * @param args the command line arguments
     */
public JButton getBtnFilm(){
    return bt_addFilm;
}

public JButton getBtnLoc(){
    return bt_addLoc;
}

public JButton getBtnCin(){
    return bt_addCin;
}

public JButton getBtnStud(){
    return bt_addStud;
}

public JButton getBtnLogout(){
    return bt_logout;
}

public JButton getBtnJadwal(){
    return btJadwal;
}

public void setLabel(String x){
    jLabel1.setText("Administrator : "+x);
}

public void addListener(ActionListener e){
    bt_addCin.addActionListener(e);
    bt_addFilm.addActionListener(e);
    bt_addLoc.addActionListener(e);
    bt_addStud.addActionListener(e);
    bt_logout.addActionListener(e);
    btJadwal.addActionListener(e);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btJadwal;
    private javax.swing.JButton bt_addCin;
    private javax.swing.JButton bt_addFilm;
    private javax.swing.JButton bt_addLoc;
    private javax.swing.JButton bt_addStud;
    private javax.swing.JButton bt_logout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
