/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;
import controllerjava.*;
import java.util.ArrayList;
import bioskop.*;
import java.awt.event.ActionListener;
import javax.swing.JButton;
/**
 *
 * @author ariq
 */
public class now_playing extends javax.swing.JFrame {

    /**
     * Creates new form now_playing
     */
    public now_playing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableNow = new javax.swing.JTable();
        cbLokasi = new javax.swing.JComboBox<>();
        cbCinema = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btExxit = new javax.swing.JButton();
        btGo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(380, 90));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("NOW PLAYING");

        tableNow.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Judul", "Tanggal", "Jam", "Harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableNow);
        if (tableNow.getColumnModel().getColumnCount() > 0) {
            tableNow.getColumnModel().getColumn(0).setResizable(false);
            tableNow.getColumnModel().getColumn(1).setResizable(false);
            tableNow.getColumnModel().getColumn(2).setResizable(false);
            tableNow.getColumnModel().getColumn(3).setResizable(false);
        }

        cbLokasi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        cbCinema.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Lokasi");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Cinema");

        btExxit.setText("Exit");
        btExxit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExxitActionPerformed(evt);
            }
        });

        btGo.setText("Go");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(245, 245, 245))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btExxit)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btGo)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbCinema, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbCinema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btGo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(btExxit)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btExxitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExxitActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_btExxitActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public String getLokasi(){
        int i = cbLokasi.getSelectedIndex();
        return cbLokasi.getItemAt(i);
    }
    
    public String getCinema(){
        int i = cbCinema.getSelectedIndex();
        return cbCinema.getItemAt(i);
    }
    
    public void setComboLoc (ArrayList <String> list){
        for (String x : list){
            cbLokasi.addItem(x);
        }
    }
    public void setComboCin (ArrayList <String> list){
        for (String x : list){
            cbCinema.addItem(x);
        }
    }

    public JButton getBtnExit(){
        return btExxit;
    }
    
    public JButton getBtnGo(){
        return btGo;
    }
    
    public void setTableJadwal(ArrayList<jadwal_film> list, String o, String p){
        int i = 0;
        for (jadwal_film x : list) {
            if (x.getNama_lokasi().equals(o) && x.getNama_bioskop().equals(p)) {
                tableNow.setValueAt(x.getJudul_film(), i, 0);
                tableNow.setValueAt(x.getTgl_tayang(), i, 1);
                tableNow.setValueAt(x.getJamtayang(), i, 2);
                tableNow.setValueAt(x.getHarga(), i, 3);
                i++;
            }//masih error
            else{
                tableNow.setValueAt("", i, 0);
                tableNow.setValueAt("", i, 1);
                tableNow.setValueAt("", i, 2);
                tableNow.setValueAt("", i, 3);
                i++;              
            }          
        }//end for
    }
    
    
    public void addListener(ActionListener e){
        btExxit.addActionListener(e);
        btGo.addActionListener(e);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExxit;
    private javax.swing.JButton btGo;
    private javax.swing.JComboBox<String> cbCinema;
    private javax.swing.JComboBox<String> cbLokasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableNow;
    // End of variables declaration//GEN-END:variables
}
