/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;

import bioskop.Studio;
import bioskop.jadwal_film;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import javax.swing.JButton;
import javax.swing.JList;

/**
 *
 * @author ariq
 */
public class pilih_jadwal extends javax.swing.JFrame {

    /**
     * Creates new form pilih_jadwal
     */
    public pilih_jadwal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JListJadwal = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextAreaDesc = new javax.swing.JTextArea();
        cbSeat = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btOrder = new javax.swing.JButton();
        btBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JListJadwal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JListJadwal.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(JListJadwal);

        TextAreaDesc.setColumns(20);
        TextAreaDesc.setRows(5);
        jScrollPane2.setViewportView(TextAreaDesc);

        cbSeat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbSeat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1A", "2A", "3A", "4A", "5A", "6A", "7A", "8A", "9A", "10A", "11A", "12A", "13A", "14A", "15A", "16A", "17A", "18A", "19A", "20A", "1B", "2B", "3B", "4B", "5B", "6B", "7B", "8B", "9B", "10B", "11B", "12B", "13B", "14B", "15B", "16B", "17B", "18B", "19B", "20B", "1C", "2C", "3C", "4C", "5C", "6C", "7C", "8C", "9C", "10C", "11C", "12C", "13C", "14C", "15C", "16C", "17C", "18C", "19C", "20C", "1D", "2D", "3D", "4D", "5D", "6D", "7D", "8D", "9D", "10D", "11D", "12D", "13D", "14D", "15D", "16D", "17D", "18D", "19D", "20D", "1E", "2E", "3E", "4E", "5E", "6E", "7E", "8E", "9E", "10E", "11E", "12E", "13E", "14E", "15E", "16E", "17E", "18E", "19E", "20E", "1F", "2F", "3F", "4F", "5F", "6F", "7F", "8F", "9F", "10F", "11F", "12F", "13F", "14F", "15F", "16F", "17F", "18F", "19F", "20F", "1G", "2G", "3G", "4G", "5G", "6G", "7G", "8G", "9G", "10G", "11G", "12G", "13G", "14G", "15G", "16G", "17G", "18G", "19G", "20G", "1H", "2H", "3H", "4H", "5H", "6H", "7H", "8H", "9H", "10H", "11H", "12H", "13H", "14H", "15H", "16H", "17H", "18H", "19H", "20H", "1J", "2J", "3J", "4J", "5J", "6J", "7J", "8J", "9J", "10J", "11J", "12J", "13J", "14J", "15J", "16J", "17J", "18J", "19J", "20J", "1K", "2K", "3K", "4K", "5K", "6K", "7K", "8K", "9K", "10K", "11K", "12K", "13K", "14K", "15K", "16K", "17K", "18K", "19K", "20K", "1L", "2L", "3L", "4L", "5L", "6L", "7L", "8L", "9L", "10L", "11L", "12L", "13L", "14L", "15L", "16L", "17L", "18L", "19L", "20L", "1M", "2M", "3M", "4M", "5M", "6M", "7M", "8M", "9M", "10M", "11M", "12M", "13M", "14M", "15M", "16M", "17M", "18M", "19M", "20M" }));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Pilih Seat");

        btOrder.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btOrder.setText("Order");

        btBack.setText("Back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btBack)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btOrder)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbSeat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbSeat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(btBack)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public String getSelectedJadwal(){
        return JListJadwal.getSelectedValue();
        //return JListJadwal.getSelectedIndex();
        
    }
    
    
    public void setDaftarJadwal(String[] x){
        JListJadwal.setListData(x);
    }
    
    public String getSeat(){
        int i = cbSeat.getSelectedIndex();
        return cbSeat.getItemAt(i);
    }
    
    public JButton getBtnOrder(){
        return btOrder;
    }
    
    public JButton getBtnBack(){
        return btBack;
    }
    
    public  JList getList(){
        return JListJadwal;
    }
    
    public void setTextDes(jadwal_film x){
        String judul = x.getJudul_film();
        String stud = x.getNomor_studio();
        String tgl  = x.getTgl_tayang();
        String jam  = x.getJamtayang();
        String hrg  = String.format("%.0f", x.getHarga());
        
        String gab = "Judul             : "+judul+"\n"
                    +"Studi              : "+stud+"\n"
                    +"Tangal          : "+tgl+"\n"
                    +"Jam Tayang  : "+jam+"\n"
                    +"Harga        : Rp."+hrg;
        TextAreaDesc.setText(gab);
    }
    
    public void addListener(ActionListener e){
        btBack.addActionListener(e);
        btOrder.addActionListener(e);
    }
    
    public void addMouseAdapter(MouseAdapter m){
        JListJadwal.addMouseListener(m);
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> JListJadwal;
    private javax.swing.JTextArea TextAreaDesc;
    private javax.swing.JButton btBack;
    private javax.swing.JButton btOrder;
    private javax.swing.JComboBox<String> cbSeat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
